owner: datalift-io
repo: status

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  cname: status.datalift.io
  logoUrl: https://raw.githubusercontent.com/datalift-io/status/master/assets/upptime-icon.svg
  name: Datalift Status
  introTitle: "Attack Surface Discovery and Monitoring Service"
  introMessage: "This is Datalift's real-time status page:"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://datalift.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - mberwanger

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
